### ISSUE TITLE
Plots don't appear in Juno's plot-pane

### ISSUE THREAD

**Issue by aviatesk** [sglyon/PlotlyJS.jl#269]
First off, thanks for your great package ! The plots are truly beautiful !

**Describe the bug**

When I run code within Juno, the plots don't appear in Juno's plot-pane, but in a new window as we run within REPL.

![image](https://user-images.githubusercontent.com/40514306/52967349-29057500-33ed-11e9-85da-d320f2c50d0c.png)

Everytime I call `plot` function the plot-pane opens but the plot itself appear in a new window outside of Atom.

When I first call `plot`, I get an deprecation error below and is it related to this issue someway ?
```
┌ Warning:   The "application/juno+plotpane" MIME type is deprecated. Please use "application/prs.juno.plotpane+html" instead.
└ @ PlotlyJS C:\Users\aviat\.julia\packages\PlotlyJS\CEJyh\src\display.jl:15
```
(FYI after I manually changed `application/juno+plotpane` to `application/prs.juno.plotpane+html` and rebuilt the package, any new window didn't appear but still plots never appeared in the plot-pane...)

**Version info**

1. output of julia command `versioninfo()`
```
julia> versioninfo()
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) m5-6Y54 CPU @ 1.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\aviat\AppData\Local\atom\app-1.34.0\atom.exe" -a
  JULIA_NUM_THREADS = 2
```

2. Output running the following in Julia 0.7 or greater: `using Pkg; pkg"status"` (if you are on Julia 0.6 or earlier run `Pkg.
```
julia> pkg"status"
    Status `C:\Users\aviat\.julia\environments\v1.0\Project.toml`
  [c52e3926] Atom v0.7.14
  [ad839575] Blink v0.10.0
  [e5e0dc1b] Juno v0.5.4
  [47be7bcc] ORCA v0.2.1
  [f0f68f2c] PlotlyJS v0.12.3
```

**Comment by sglyon** [comment]
Thanks for reporting! I'm going to call in an expert here.

@pfitzseb does this look familiar to you? Perhaps related to changes regarding pushing a `PlotlyJSDisplay` onto the display stack?

**Comment by pfitzseb** [comment]
I'm reasonably sure that happens because the WebIO integration in Juno is kinda broken right now. Will take another look at that soonish.

**Comment by aviatesk** [comment]
@sglyon @pfitzseb Thanks for replying me back !
Ok, hope the bug will be successfully removed.

Since I'm in sort of urgent need of it, maybe downgrading Juno.jl package can temporary solve the problem ??

**Comment by aviatesk** [comment]
Oh, I see. PlotlyJS.jl plots work with lower than Atom.jl@0.7.12 but instead autocomplete doesn't work.

**Comment by InfernalWAVE** [comment]
Any update here? Plotly is working great for plotting figures from the Control Systems module, but cannot get them to appear in the Juno pane.

**Comment by sglyon** [comment]
I haven't seen any new info , sorry about that. 

Maybe someone else has worked on it?

**Comment by DhruvaSambrani** [comment]
> I'm reasonably sure that happens because the WebIO integration in Juno is kinda broken right now. Will take another look at that soonish.

This should be fixed. Can someone check?

**Comment by josephmarturano** [comment]
For me, PlotlyJS plots are still showing up as a pop-up window, and not in the Juno plot pane. I am running Juno 0.7.0, WebIO 0.8.9, and PlotlyJS 0.12.5.

When I run the following:
`using WebIO; node(:div, "Hello, World")`

I see "Hello world" in the plot pane.

But then when I run the following:
`using PlotlyJS; plot([1,2,3], rand(3))`

I see a pop-up window with a plot. I could be doing something wrong.
